create table if not exists public.responses (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 nama text not null,
 status text not null check(status in ('Siswa','Orang Tua/Wali','Guru')),
 kelas text not null check(kelas in ('Kelas I','Kelas II','Kelas III','Kelas IV','Kelas V','Kelas VI')),
 jawaban jsonb not null,
 saran text
);
alter table public.responses enable row level security;
drop policy if exists public_insert_responses on public.responses;
create policy public_insert_responses on public.responses for insert to anon with check(true);
drop policy if exists authenticated_read_responses on public.responses;
create policy authenticated_read_responses on public.responses for select to authenticated using(true);
